In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
ser = pd.Series(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
data = pd.DataFrame(ser)
data

0
0  a
1  b
2  c
3  d
4  e
5  f
6  g
7  h
8  i
9  j

## Example for a KFold Cross Validation

- The idea behind the KFold cross validation is to create multiple set of Train and Test Datasets by specifiying the number of splits that we want.

In [14]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [15]:
list(kf.split(data))

[(array([4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3])),
 (array([0, 1, 2, 3, 7, 8, 9]), array([4, 5, 6])),
 (array([0, 1, 2, 3, 4, 5, 6]), array([7, 8, 9]))]

In [16]:
#i = 1
for train, test in kf.split(data):
    #print("Iteratoion No:", i)
    print("Train : ", train, "Test : ", test)

Train :  [4 5 6 7 8 9] Test :  [0 1 2 3]
Train :  [0 1 2 3 7 8 9] Test :  [4 5 6]
Train :  [0 1 2 3 4 5 6] Test :  [7 8 9]


In [17]:
from sklearn.model_selection import cross_val_score

In [19]:
list(kf.split(data))[1]

(array([0, 1, 2, 3, 7, 8, 9]), array([4, 5, 6]))