## Using Kfold Cross validation you can select the model with best accuracy

- I want to figure out, whether Logistic Regression gives best accuracy on Health_Insurance data or KNeighborsClassier gives best accuracy on this data

## Loading the standard libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

## Loading the data

In [2]:
data = pd.read_csv('Health_Insurance.csv')
data.head()

Age  Purchased
0   19          0
1   35          0
2   26          0
3   27          0
4   19          0

In [3]:
data.shape

(400, 2)

## Seperate X and y

In [4]:
X = data[['Age']]
y = data['Purchased']

## Perform the KFold splits

In [5]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 10)

## Import the models

In [6]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()

In [7]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

## Apply the models on the KFolds

- cross_val_score(ML_model, X, y, cv = n_split)

In [10]:
from sklearn.model_selection import cross_val_score
acc_lr = cross_val_score(log_reg, X, y, cv = kf)
acc_lr

array([0.95 , 0.9  , 0.925, 0.9  , 0.925, 0.6  , 0.775, 0.675, 0.85 ,
       0.9  ])

In [11]:
knn_acc = cross_val_score(knn, X, y, cv = kf)
knn_acc

array([0.9  , 0.875, 0.85 , 0.825, 0.925, 0.6  , 0.775, 0.625, 0.8  ,
       0.8  ])

In [12]:
acc_lr.mean()

0.8400000000000001

In [13]:
knn_acc.mean()

0.7975

#### Looking at the mean accuracies of Logistic Regression and KNeighborsClassifier, the mean of Logistic Regression is higher than KNeighborsClassifier.

- Conclusion:
1. For this health Insurance dataset, Logistic Regression is the best Machine Learning model

In [14]:
list(kf.split(data))[0]

(array([ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
        170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
        183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
        196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
        209, 210, 211, 212, 213, 214, 215, 216, 217