In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
data = pd.read_csv('mnist_test.csv')
data.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      7    0    0    0    0    0    0    0    0    0  ...      0      0   
1      2    0    0    0    0    0    0    0    0    0  ...      0      0   
2      1    0    0    0    0    0    0    0    0    0  ...      0      0   
3      0    0    0    0    0    0    0    0    0    0  ...      0      0   
4      4    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

## Seperate X and y

In [4]:
X = data.drop('label', axis = 1)
y = data['label']

## Divide data into train_test_split

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)


## Apply Decision as a stand alone ML model

In [7]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()

In [8]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [9]:
y_pred_standalone = dtc.predict(X_test)
y_pred_standalone

array([9, 1, 7, ..., 2, 7, 9], dtype=int64)

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_pred_standalone, y_test))
print(confusion_matrix(y_test, y_pred_standalone))
print(classification_report(y_test, y_pred_standalone))

0.8024
[[211   0   4   5   1   3   6   2   7   3]
 [  0 244   2   5   2   2   1   1   2   4]
 [  3  10 189   8   8   4   1   8  12   7]
 [  3   4  15 196   5  13   2   6  17   9]
 [  5   2   3   3 203   2   6   6   6  10]
 [  9   3   9  16   6 187   2   7   6   7]
 [  6   4  11   2  10   5 185   2   4   4]
 [  0   3   3   7   5   2   2 204   1  11]
 [  6   7  14  12   5   7   4   5 178   9]
 [  1   1   6   6  17   4   1   8   6 209]]
              precision    recall  f1-score   support

           0       0.86      0.87      0.87       242
           1       0.88      0.93      0.90       263
           2       0.74      0.76      0.75       250
           3       0.75      0.73      0.74       270
           4       0.77      0.83      0.80       246
           5       0.82      0.74      0.78       252
           6       0.88      0.79      0.84       233
           7       0.82      0.86      0.84       238
           8       0.74      0.72      0.73       247
           9       0.

## Bagging Classifier on MNIST

In [13]:
from sklearn.ensemble import BaggingClassifier
bc = BaggingClassifier(base_estimator = dtc, max_samples = 100, random_state = 42)

In [14]:
bc.fit(X_train, y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(), max_samples=100,
                  random_state=42)

In [16]:
y_pred_bc = bc.predict(X_test)
y_pred_bc

array([4, 1, 7, ..., 2, 4, 4], dtype=int64)

In [17]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_pred_bc, y_test))
print(confusion_matrix(y_test, y_pred_bc))
print(classification_report(y_test, y_pred_bc))

0.714
[[225   4   3   1   0   2   2   5   0   0]
 [  0 259   0   0   0   1   1   0   2   0]
 [  9  34 155  10   5   3   8  14   7   5]
 [  3  15   9 213   4  11   0   4   2   9]
 [  5   8  15   3 185   2   8   1   1  18]
 [ 14  22   3  47  12 127   7   9   1  10]
 [ 19  11  30   4   9   6 148   0   6   0]
 [  0  20   7   2  18   2   1 174   2  12]
 [  6  40  17  24   4   7   2   7 123  17]
 [  9   5   9  10  34   3   2   7   4 176]]
              precision    recall  f1-score   support

           0       0.78      0.93      0.85       242
           1       0.62      0.98      0.76       263
           2       0.62      0.62      0.62       250
           3       0.68      0.79      0.73       270
           4       0.68      0.75      0.72       246
           5       0.77      0.50      0.61       252
           6       0.83      0.64      0.72       233
           7       0.79      0.73      0.76       238
           8       0.83      0.50      0.62       247
           9       0.7

## RandomForestClassifier

In [18]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 50)

In [19]:
rfc.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50)

In [20]:
y_pred_rfc = rfc.predict(X_test)
y_pred_rfc

array([9, 1, 7, ..., 2, 7, 4], dtype=int64)

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_pred_rfc, y_test))
print(confusion_matrix(y_test, y_pred_rfc))
print(classification_report(y_test, y_pred_rfc))

0.9504
[[239   0   0   0   0   0   2   0   1   0]
 [  0 260   1   0   0   1   1   0   0   0]
 [  1   0 235   2   1   1   3   5   1   1]
 [  0   0   7 251   0   2   0   4   3   3]
 [  0   0   1   0 237   1   2   1   0   4]
 [  4   2   1   5   1 237   2   0   0   0]
 [  3   1   2   0   0   1 226   0   0   0]
 [  0   1   6   0   2   0   0 225   0   4]
 [  1   5   1   3   2   5   2   2 223   3]
 [  2   0   2   3   7   0   0   2   0 243]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.97       242
           1       0.97      0.99      0.98       263
           2       0.92      0.94      0.93       250
           3       0.95      0.93      0.94       270
           4       0.95      0.96      0.96       246
           5       0.96      0.94      0.95       252
           6       0.95      0.97      0.96       233
           7       0.94      0.95      0.94       238
           8       0.98      0.90      0.94       247
           9       0.

### Boosting

In [25]:
## Note : Specifying max_depth = 1 we are intensionally making the decisiontreeclassifier a weak learner

from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(max_depth = 1)

In [27]:
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier(base_estimator = dtc, n_estimators = 50, random_state = 42)

In [28]:
abc.fit(X_train, y_train)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1),
                   random_state=42)

In [29]:
y_pred_abc = abc.predict(X_test)
y_pred_abc

array([4, 1, 7, ..., 6, 5, 4], dtype=int64)

In [30]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_pred_abc, y_test))
print(confusion_matrix(y_test, y_pred_abc))
print(classification_report(y_test, y_pred_abc))

0.682
[[205   0   5   0   0  22  10   0   0   0]
 [  0 243   0   9   0   2   1   2   6   0]
 [  3  21 169   4   7   5  19  14   7   1]
 [  4   5   9 153   4  28   4   4  51   8]
 [  2   1   5   3 172  12   8  14   8  21]
 [  3   4   1  14   8 172   8   4  27  11]
 [ 12   5   8   1  25  16 151   4   7   4]
 [  1   2   9   0   8   3   1 175   5  34]
 [  1  15   7  19   5  20   6   7 158   9]
 [  1   0   7   3  96   5   1  18  21 107]]
              precision    recall  f1-score   support

           0       0.88      0.85      0.86       242
           1       0.82      0.92      0.87       263
           2       0.77      0.68      0.72       250
           3       0.74      0.57      0.64       270
           4       0.53      0.70      0.60       246
           5       0.60      0.68      0.64       252
           6       0.72      0.65      0.68       233
           7       0.72      0.74      0.73       238
           8       0.54      0.64      0.59       247
           9       0.5

### Voting Classifier : Used to apply multiple ML models on the data and select the one with high accuracy

In [35]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
from sklearn.svm import SVC
svc = SVC()
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()

In [36]:
from sklearn.ensemble import VotingClassifier
vc = VotingClassifier(estimators = [('log_reg', lr), ('sup_vec', svc), ('tree', dtc)])

In [37]:
vc.fit(X_train, y_train)

VotingClassifier(estimators=[('log_reg', LogisticRegression()),
                             ('sup_vec', SVC()),
                             ('tree', DecisionTreeClassifier())])

In [39]:
y_pred_vc = vc.predict(X_test)
y_pred_vc

array([9, 1, 7, ..., 2, 7, 9], dtype=int64)

In [40]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_pred_vc, y_test))
print(confusion_matrix(y_test, y_pred_vc))
print(classification_report(y_test, y_pred_vc))

0.9384
[[240   0   0   0   0   0   1   0   1   0]
 [  0 260   1   0   0   2   0   0   0   0]
 [  1   2 238   2   1   0   3   1   2   0]
 [  1   2   6 252   0   5   0   0   2   2]
 [  0   1   3   1 234   0   2   2   1   2]
 [  4   4   3   7   2 225   4   0   2   1]
 [  4   1   4   0   0   1 222   0   1   0]
 [  0   2   6   3   5   0   0 218   0   4]
 [  2   6   6   4   3   4   0   0 219   3]
 [  3   1   1   3   7   2   0   3   1 238]]
              precision    recall  f1-score   support

           0       0.94      0.99      0.97       242
           1       0.93      0.99      0.96       263
           2       0.89      0.95      0.92       250
           3       0.93      0.93      0.93       270
           4       0.93      0.95      0.94       246
           5       0.94      0.89      0.92       252
           6       0.96      0.95      0.95       233
           7       0.97      0.92      0.94       238
           8       0.96      0.89      0.92       247
           9       0.

In [42]:
vc.named_estimators

{'log_reg': LogisticRegression(),
 'sup_vec': SVC(),
 'tree': DecisionTreeClassifier()}